### ISSUE TITLE
Please check the website content

### ISSUE THREAD

**Issue by verku** [NBISweden/workshop-snakemake-byoc#9]
Please read through these documents:

https://github.com/NBISweden/workshop-snakemake-byoc/blob/devel/index.md
https://github.com/NBISweden/workshop-snakemake-byoc/blob/devel/schedule.md
https://github.com/NBISweden/workshop-snakemake-byoc/blob/devel/precourse.md

Let me know if you have any suggestions for changes of content (ideally, through a pull request)!

To put these pages online, I'll merge the devel branch into the master branch once we're happy.

**Comment by fasterius** [comment]
Looks very good! I added some very minor changes in spelling and text-formatting.

**Comment by verku** [comment]
I've added some info about feedback and coding sessions.
